---
- name: "Creates backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: dist.zip
    dest: "~/backend/dist.zip"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend
    unzip dist.zip
    rm -rf dist.zip
- name: "Install NPM"
  shell: |
    cd ~/backend
    npm install
- name: "Executing node"
  shell: |
    export
    cd ~/backend
    pm2 start npm -- start
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
