---
- name: "create ~/backend"
  ansible.builtin.file:
    path: ~/backend
    state: directory
    mode: '0755'

- name: Extract artifact.tar.gz into ~/backend 
  unarchive:  
    src: artifact.tar.gz  
    dest: ~/backend/

- name: "start server"
  shell: |
    cd ~/backend/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start
